apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ocpStuff
    resourcetype: build
  name: ocpStuff-build
spec:
  failedBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ocpStuff-build:latest
  postCommit: {}
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "500m"
      memory: 500Mi
  runPolicy: Serial
  source:
    contextDir: C:\Users\joaor\Downloads\myReps\ocpStuffVS\ocpStuff
    git:
      ref: master
      uri: https://github.com/joaorr1/ocpStuff.git
    type: Git
 strategy:
  type: "Source"
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "incremental-image:latest" 
    incremental: true 
  successfulBuildsHistoryLimit: 5
