apiVersion: v1
kind: BuildConfig
metadata:
  name: angular-sample-build
spec:
  source:
    git:
      uri: 'https://github.com/joaorr1/ocpStuff'
    type: Git
  triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
    - type: ImageChange
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk-11-rhel7:1.0'
        namespace: openshift
      output: null
      to:
        kind: ImageStreamTag
        name: 'angular:latest'
    type: Source